version: '3.0'
services:
  bots:
    build: .
    env_file: .
    ports:
      - "80:80"
  db:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    volumes:
      - "~/db-data:/var/lib/postgresql/data"

