version: '3.0'
services:
  bots1:
    restart: always
    build: .
    env_file: .env
    ports:
      - "8082:8082"

  # signup:
  #   restart: always
  #   build: .
  #   command: "npm run serve"
  #   ports:
  #     - "80:80"
  db:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    volumes:
      - "~/db-data:/var/lib/postgresql/data"
  redis:
    image: redis
    restart: always
    ports: 
     - "6379:6379"

