version: "3.0"
services:
  db:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"
    volumes:
      - "~/db-data:/var/lib/postgresql/data"
  smm:
    restart: always
    build: .
    command: npm run smm
    env_file: .env
  neuro:
    restart: always
    build: .
    command: npm run neuro
    env_file: .env
  spambot:
    restart: always
    build: .
    command: npm run spambot
    env_file: .env
  mailer:
    restart: always
    build: .
    command: npm run mailer
    env_file: .env

  invest:
    restart: always
    build:
      context: .
      dockerfile: ./src/investApi/Dockerfile
    env_file: .env
    ports:
      -"6667:6667"
  # support:
  #   restart: always
  #   build: .
  #   command: npm run support
  #   env_file: .env
